hanlin/hanlin/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls', namespace='main')),
    path('shop/', include('shop.urls', namespace='shop')),
    path('account/', include('account.urls', namespace='account')),
    path('new/', include('new.urls', namespace='new')),
    path('order/', include('order.urls', namespace='order')),
    re_path('.*', views.main)
]

hanlin/new/urls.py
from django.urls import path
from new import views


app_name = 'new'
urlpatterns = [
    path('', views.new, name='new'),
    path('articleCreate/', views.articleCreate, name='articleCreate'),
    path('articleRead/<int:articleId>', views.articleRead, name='articleRead'),
    path('articleUpdate/<int:articleId>', views.articleUpdate, name='articleUpdate'),
    path('articleDelete/<int:articleId>', views.articleDelete, name='articleDelete'),
]

hanlin/order/urls.py
from django.urls import path
from order import views


app_name = 'order'
urlpatterns = [
    path('', views.order, name='order'),
    path('orderDelete/<int:orderId>', views.orderDelete, name='orderDelete'),
]

hanlin/shop/urls.py
from django.urls import path
from shop import views


app_name = 'shop'
urlpatterns = [
    path('', views.shop, name='shop'),
    path('branchCreate/', views.branchCreate, name='branchCreate'),
    path('branchRead/<int:branchId>', views.branchRead, name='branchRead'),
    path('plantRead/<int:branchId>/<int:plantId>', views.plantRead, name='plantRead'),
    path('plantCreate/<int:branchId>', views.plantCreate, name='plantCreate'),
    path('branchUpdate/<int:branchId>', views.branchUpdate, name='branchUpdate'),
    path('plantUpdate/<int:branchId>/<int:plantId>', views.plantUpdate, name='plantUpdate'),
    path('branchDelete/<int:branchId>', views.branchDelete, name='branchDelete'),
    path('plantDelete/<int:plantId>', views.plantDelete, name='plantDelete'),
    path('plantSearch/', views.plantSearch, name='plantSearch'),
    path('plantDiscount/<int:branchId>/<int:plantId>', views.plantDiscount, name='plantDiscount'),
    path('plantBuy/<int:plantId>', views.plantBuy, name='plantBuy'),
]

hanlin/order/models.py
from django.db import models
from account.models import User
from shop.models import Plant
# Create your models here.

class Order(models.Model):
    customer = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=128)
    phone = models.CharField(max_length=128)
    address = models.CharField(max_length=128, blank=True, null=True)
    email = models.EmailField()
    plant = models.ForeignKey(Plant, on_delete=models.CASCADE)
    totalPrice = models.IntegerField()
    payMethod = models.CharField(max_length=128)
    pubDateTime = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.name +'-'+ self.plantName
    
    class Meta:
        ordering = ['-pubDateTime']
    
    

hanlin/order/forms.py
from django import forms
from order.models import Order
from cProfile import label


PAYMETHOD = [('ATM','ATM'), ('貨到付款','貨到付款'), ('PChome','PChome')]
class OrderForm(forms.ModelForm):
    name = forms.CharField(label='姓名', max_length=128)
    phone = forms.CharField(label='手機', max_length=128)
    address = forms.CharField(label='地址', max_length=128)
    email = forms.EmailField(label='信箱')
    payMethod = forms.ChoiceField(label='付款方式', choices=PAYMETHOD, widget=forms.RadioSelect())
    
    class Meta:
        model = Order
        exclude = ['customer','pubDateTime','plant','totalPrice']

hanlin/order/views.py
from django.shortcuts import render, redirect, get_object_or_404
from order.models import Order
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from main.views import admin_required
# Create your views here.

@login_required
def order(request):
    orders = Order.objects.all()
    context = {'orders':orders, 'userOrders':Order.objects.filter(customer=request.user)}
    return render(request, 'order/order.html', context)

@admin_required
def orderDelete(request, orderId):
    if request.method == 'GET':
        return order(request)
    #POST
    order = get_object_or_404(Order, id=orderId)
    order.plant.buyes.remove(order.customer)
    order.plant.inventory = order.plant.inventory+1
    order.plant.save()
    order.delete()
    messages.success(request, '訂單已取消')
    return redirect('order:order')

hanlin/order/templates/order/order.html
{% extends 'main/base.html' %}
{% load staticfiles %}
{% block content %}
{% include 'main/messages.html' %}
<h2 class="four">訂單資訊</h2>
<div class="tableDiv">
<table class="table table-striped table-hover">
<tr>
<th>日期</th>
<th>商品</th>
<th>顧客</th>
<th>電話</th>
<th>總價</th>
</tr>
{% if user.is_superuser %}
{% for order in orders %}
<tr>
<td>{{ order.pubDateTime }}</td>
<td><a href="{% url 'shop:plantRead' order.plant.branch.id order.plant.id %}">{{　order.plant.plantName }}</a></td>
<td>{{　order.name }}</td>
<td>{{ order.phone }}</td>
<td>{{ order.totalPrice }}
{% if user.is_superuser %}
      <form class="inlineBlock" method="post" action="{% url 'order:orderDelete' order.id %}">
      {% csrf_token %}
      <input class="btn deleteConfirm" type="submit" value="刪除">
      </form>
{% endif %} 
</td>
</tr>
{% endfor %}
{% else %}
{% for order in userOrders %}
<tr>
<td>{{ order.pubDateTime }}</td>
<td><a href="/">{{　order.plant.plantName }}</a>
</td>
<td>{{　order.name }}</td>
<td>{{ order.phone }}</td>
<td>{{ order.totalPrice }}
{% if user.is_superuser %}
      <form class="inlineBlock" method="post" action="{% url 'order:orderDelete' order.id %}">
      {% csrf_token %}
      <input class="btn deleteConfirm" type="submit" value="刪除">
      </form>
{% endif %} 
</td>
</tr>
{% endfor %}
{% endif %}
</table>
</div>
{% endblock %}