hanlin/hanlin/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls', namespace='main')),
    path('shop/', include('shop.urls', namespace='shop')),
    path('account/', include('account.urls', namespace='account')),
    path('new/', include('new.urls', namespace='new')),
    path('order/', include('order.urls', namespace='order')),
    re_path('.*', views.main)
]

hanlin/new/urls.py
from django.urls import path
from new import views


app_name = 'new'
urlpatterns = [
    path('', views.new, name='new'),
    path('articleCreate/', views.articleCreate, name='articleCreate'),
    path('articleRead/<int:articleId>', views.articleRead, name='articleRead'),
    path('articleUpdate/<int:articleId>', views.articleUpdate, name='articleUpdate'),
    path('articleDelete/<int:articleId>', views.articleDelete, name='articleDelete'),
]

hanlin/shop/urls.py
from django.urls import path
from shop import views


app_name = 'shop'
urlpatterns = [
    path('', views.shop, name='shop'),
    path('branchCreate/', views.branchCreate, name='branchCreate'),
    path('branchRead/<int:branchId>', views.branchRead, name='branchRead'),
    path('plantRead/<int:branchId>/<int:plantId>', views.plantRead, name='plantRead'),
    path('plantCreate/<int:branchId>', views.plantCreate, name='plantCreate'),
    path('branchUpdate/<int:branchId>', views.branchUpdate, name='branchUpdate'),
    path('plantUpdate/<int:branchId>/<int:plantId>', views.plantUpdate, name='plantUpdate'),
    path('branchDelete/<int:branchId>', views.branchDelete, name='branchDelete'),
    path('plantDelete/<int:plantId>', views.plantDelete, name='plantDelete'),
    path('plantSearch/', views.plantSearch, name='plantSearch'),
    path('plantDiscount/<int:branchId>/<int:plantId>', views.plantDiscount, name='plantDiscount'),
    path('plantBuy/<int:plantId>', views.plantBuy, name='plantBuy'),
]

hanlin/shop/models.py
from django.db import models
from account.models import User
# Create your models here.

class Branch(models.Model):
    branchName = models.CharField(max_length=128, unique=True)
    url = models.CharField(max_length=128)
    
    def __str__(self):
        return self.branchName
    
class Plant(models.Model):
    branch = models.ForeignKey(Branch, on_delete=models.CASCADE)
    plantName = models.CharField(max_length=128)
    code = models.CharField(max_length=128, unique=True)
    price = models.IntegerField()
    inventory = models.IntegerField()
    pubDateTime = models.DateTimeField(auto_now_add=True)
    url = models.CharField(max_length=128)
    hot = models.BooleanField()
    discount = models.IntegerField()
    newPrice = models.IntegerField()
    buyes = models.ManyToManyField(User)
    
    def __str__(self):
        return self.branch.branchName +'-'+ self.plantName
    
    class Meta:
        ordering = ['-pubDateTime']
        

hanlin/shop/forms.py
from django import forms
from shop.models import Branch, Plant
from cProfile import label

class BranchForm(forms.ModelForm):
    branchName = forms.CharField(label='種類名', max_length=128)
    url = forms.CharField(label='圖片檔名', max_length=128)
    
    class Meta:
        model = Branch
        fields = ['branchName','url']
        

class PlantForm(forms.ModelForm):
    plantName = forms.CharField(label='品名', max_length=128)
    code = forms.CharField(label='編號', max_length=128)
    price = forms.IntegerField(label='價格',)
    inventory = forms.IntegerField(label='庫存')
    url = forms.CharField(label='圖片檔名', max_length=128)
    
#     def save(self, commit=True):
#         plant = super(PlantForm, self).save(commit=False)
    
    class Meta:
        model = Plant
        exclude = ['branch', 'pubDateTime','discount','newPrice','buyes']

hanlin/shop/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models.query_utils import Q
from django.shortcuts import render, redirect, get_object_or_404

from account.forms import UserForm
from account.models import User
from main.views import admin_required
from shop.forms import BranchForm, PlantForm
from order.forms import OrderForm
from shop.models import Branch, Plant



# Create your views here.
def shop(request):
    branches = {}
    for branch in Branch.objects.all():
        branches.update({branch:Plant.objects.filter(branch=branch)})
    context = {'branches':branches}
    
    return render(request, 'shop/shop.html',context)
@admin_required
def branchCreate(request):
    template = 'shop/branchCreateUpdate.html'
    if request.method == 'GET':
        return render(request, template, {'branchForm':BranchForm()})
    
    #POST
    branchForm = BranchForm(request.POST)
    if not branchForm.is_valid():
        return render(request, template,{'branchForm':branchForm})
    branchForm.save()
    messages.success(request, '類別已新增')
    return redirect('shop:shop')

def branchRead(request, branchId):
    branch = get_object_or_404(Branch, id=branchId)
    context = {
        'branch':branch,
        'plants':Plant.objects.filter(branch=branch)
    }
    return render(request, 'shop/branchRead.html', context)

def plantRead(request, plantId, branchId):
    branch = get_object_or_404(Branch, id=branchId)
    plant = get_object_or_404(Plant, id=plantId)
    context = {
        'plants':Plant.objects.filter(branch=branch),
        'plant':plant,
        'branch':branch
    }
    return render(request, 'shop/plantRead.html', context)
@admin_required
def plantCreate(request, branchId):
    template = 'shop/plantCreateUpdate.html'
    branch = get_object_or_404(Branch, id=branchId)
    if request.method == 'GET':
        return render(request, template, {'plantForm':PlantForm(),'branch':branch})
    
    #POST
    plantForm = PlantForm(request.POST)
    if not plantForm.is_valid():
        return render(request, template, {'plantForm':plantForm})
    plant = plantForm.save(commit=False)
    plant.branch = branch
    plant.discount = 0
    plant.newPrice = 0
    plant.save()
    messages.success(request, '商品已新增')
    return redirect('shop:shop')

@admin_required
def branchUpdate(request, branchId):
    branch = get_object_or_404(Branch, id=branchId )
    template = 'shop/branchCreateUpdate.html'
    if request.method == 'GET':
        branchForm = BranchForm(instance=branch)
        return render(request, template, {'branchForm':branchForm})
    
    #POST
    branchForm = BranchForm(request.POST, instance=branch)
    if not branchForm.is_valid():
        return render(request, template, {'branchForm':branchForm})
    branchForm.save()
    messages.success(request, '類別名修改成功')
    return redirect('shop:branchRead', branchId=branchId)

@admin_required
def plantUpdate(request, branchId, plantId):
    branch = get_object_or_404(Branch, id=branchId)
    plant = get_object_or_404(Plant, id=plantId)
    context = {'branch':branch, 'plant':plant}
    template = 'shop/plantCreateUpdate.html'
    if request.method == 'GET':
        context.update({'plantForm':PlantForm(instance=plant)})
        return render(request, template, context)
    
    #POST
    plantForm = PlantForm(request.POST, instance=plant)
    if not plantForm.is_valid():
        return render(request, template, {'plantForm':plantForm})
    plantForm.save()
    messages.success(request, '商品已修改')
    return redirect('shop:plantRead', branchId=branchId, plantId=plantId)

@admin_required
def branchDelete(request, branchId):
    if request.method == 'GET':
        return shop(request)
    
    #POST
    branch = get_object_or_404(Branch, id=branchId)
    branch.delete()
    messages.success(request, '類別已刪除')
    return redirect('shop:shop')

@admin_required
def plantDelete(request, plantId):
    if request.method == 'GET':
        return shop(request)
    
    #POST
    plant = get_object_or_404(Branch, id=plantId)
    plant.delete()
    messages.success(request, '類別已刪除')
    return redirect('shop:shop')

def plantSearch(request):
    searchTerm = request.GET.get('searchTerm')
    plants = Plant.objects.filter(Q(plantName__icontains=searchTerm) | Q(code__icontains=searchTerm))
    context = {'plants':plants, 'searchTerm':searchTerm}
    return render(request, 'shop/plantSearch.html', context)

@admin_required
def plantDiscount(request, plantId, branchId):
    branch = get_object_or_404(Branch, id=branchId)
    discount = int(request.GET.get('discount'))
    plant = get_object_or_404(Plant, id=plantId)
    
    if not discount:
        discountPrice = 0
    else:
        plant.discount = discount
        discountPrice = plant.price*discount/10
        plant.newPrice = discountPrice
        plant.save()
   
    
    context = {
        'plants':Plant.objects.filter(branch=branch),
        'plant':plant,
        'branch':branch,
    }

    return render(request, 'shop/plantRead.html', context)

@login_required
def plantBuy(request, plantId):
    template = 'shop/buyInfo.html'
    plant = get_object_or_404(Plant, id=plantId)
    context = {}
    if request.method == 'GET':
        context.update({'plant':plant,'orderForm':OrderForm(initial={'name':request.user.fullName, 
                                                                     'email':request.user.email, 
                                                                     'address':request.user.address, 
                                                                     'plantName':plant.plantName})})
        return render(request, template, context)

    # POST
    orderForm = OrderForm(request.POST)
    print(orderForm)
    if not orderForm.is_valid():
        return render(request, template, {'plant':plant,'orderForm':orderForm})
    if plant.newPrice:
        realPrice = plant.newPrice
    else:
        realPrice = plant.price
    order = orderForm.save(commit=False)
    order.plant = plant
    order.customer = request.user
    order.totalPrice = realPrice
    order.save()
    messages.success(request, '購買成功')
    if request.user not in plant.buyes.all():
        plant.buyes.add(request.user)
        plant.inventory = plant.inventory-1
        plant.save()
    return redirect('shop/shop.html')

    
    

hanlin/shop/templates/shop/branchCreate.html
{% extends 'main/base.html' %}
{% load staticfiles %}
{% block css %}<link rel="stylesheet" href="{% static 'shop/css/shop.css' %}">{% endblock %}
{% block content %}
<h2>新增類別</h2>
<form id="form" method="post" action="{% url 'shop:branchCreate' %}">
{% csrf_token %}
{{ branchForm.as_p }}
<input class="btn' type="submit" value="送出">
<a class="btn" href="{% url 'shop:shop' %}">放棄</a>
</form>
{% endblock %}

hanlin/shop/templates/shop/branchCreateUpdate.html
{% extends 'main/base.html' %}
{% load staticfiles %}
{% block css %}<link rel="stylesheet" href="{% static 'shop/css/shop.css' %}">{% endblock %}
{% block content %}
{% if branchForm.instance.id %}
<h2>修改類別</h2>
<form id="form" method="post" action="{% url 'shop:branchUpdate' branchForm.instance.id %}">
{% else %}
<h2>新增類別</h2>
<form id="form" method="post" action="{% url 'shop:branchCreate' %}">
{% endif %}
{% csrf_token %}
{{ branchForm.as_p }}
<input class="btn" type="submit" value="送出">
<a class="btn" href="{% url 'shop:shop' %}">放棄</a>
</form>
{% endblock %}

hanlin/shop/templates/shop/branchRead.html
{% extends 'main/base.html' %}
{% load staticfiles %}
{% block css %}<link rel="stylesheet" href="{% static 'shop/css/shop.css' %}"> {% endblock %}
{% block content %}
{% include 'main/messages.html' %}
<aside>
<ul>
    <li class="classheader">{{ branch.branchName }}
    {% if user.is_superuser %}
    <a class="edit" href="{% url 'shop:branchUpdate' branch.id %}"><img class="icon" src="{% static 'main/img/edit-regular.svg' %}"></a>
    {% endif %}
    </li>
{% for plant in plants %}    
    <li><a href="{% url 'shop:plantRead' branch.id plant.id %}">{{ plant.plantName }}</a></li>
{% endfor %}
  </ul>
</aside>

<div id="contentRight">
{% for plant in plants %}
  <div class="plantImg"><P>{{ plant.plantName }}</P><a href="{% url 'shop:plantRead' branch.id plant.id %}"><img src="/static/main/img/{{ plant.url }}"></a>
    <p>
    $ {{ plant.price }}<br>
    庫存 {{ plant.inventory }}
    </p>  
  </div> 
{% endfor %}
{% if user.is_superuser %}
<div class="plantImg"><P>New</P><a class='newItem' href="{% url 'shop:plantCreate' branch.id %}">+</a></div>
{% endif %}
</div>


{% endblock %}

hanlin/shop/templates/shop/buyInfo.html
{% extends 'main/base.html' %}
{% load staticfiles %}
{% block content %}
<h2 class="four">購買商品明細</h2>

<ul class="detail">
<li><p>品名 : {{ plant.plantName }}</p></li>  
{% if plant.newPrice %}
<li><p><b>原價</b> $ <del>{{ plant.price }}</del></p></li>
<li><p><b>優惠價</b> $ {{ plant.newPrice }}</p></li>
{% else %}
<li><p>$ {{ plant.price }}</p></li>
{% endif %}
<li><p>編碼 {{ plant.code }}</p></li>      
<li><p>總計:NT$ {{ plant.newPrice }}元</p></li>     
</ul>

<h2 class="four">訂購人</h2>

<ul class="detail">
<li><p>姓名 : {{ user.fullName }}</p></li>  
<li><p>住址 : {{ user.address }}</p></li>
<li><p>信箱 : {{ user.email }}</p></li>          
</ul>

<h2 class="four">收件人</h2>
<form method="post" action="{% url 'shop:plantBuy' plant.id %}">
  {% csrf_token %}
  <p>{{ orderForm.name.label }}：{{ orderForm.name }}</p>
  <p>{{ orderForm.email.label }}：{{ orderForm.email }}</p>
  <p>{{ orderForm.address.label }}：{{ orderForm.address }}</p>
  <p>{{ orderForm.phone.label }}：{{ orderForm.phone }}</p>
  <div class="pay">{{ orderForm.payMethod.label }}：{{ orderForm.payMethod }}</div>
  <input class="btn" type="submit" value="確認">
</form>


{% endblock %}

hanlin/shop/templates/shop/plantCreateUpdate.html
{% extends 'main/base.html' %}
{% load staticfiles %}
{% block css %}<link rel="stylesheet" href="{% static 'shop/css/shop.css' %}">{% endblock %}
{% block content %}
{% if plantForm.instance.id %}
<h2>修改商品</h2>
<form id="form" method="post" action="{% url 'shop:plantUpdate' branch.id plant.id %}">
{% else %}
<h2>新增商品</h2>
<form id="form" method="post" action="{% url 'shop:plantCreate' branch.id %}">
{% endif %}
{% csrf_token %}
{{ plantForm.as_p }}
<input class="btn" type="submit" value="送出">
<a class="btn" href="{% url 'shop:shop' %}">放棄</a>
</form>
{% endblock %}

hanlin/shop/templates/shop/plantRead.html
{% extends 'main/base.html' %}
{% load staticfiles %}
{% block css %}<link rel="stylesheet" href="{% static 'shop/css/shop.css' %}"> {% endblock %}
{% block content %}
{% include 'main/messages.html' %}
<aside>
<ul>
    <li class="classheader"><a href="{% url 'shop:branchRead' branch.id %}">{{ branch.branchName }}</a></li>
{% for p in plants %}    
    <li><a href="{% url 'shop:plantRead' branch.id p.id %}">{{ p.plantName }}</a></li>
{% endfor %}
  </ul>
</aside>

<div id="contentRight">
    
    <div id="bigplantImg"><img src="/static/main/img/{{ plant.url }}"></div>
    <div id="info">
    <p>
    <h1>{{ plant.plantName }}
    {% if user.is_superuser %}
    <a class="edit" href="{% url 'shop:plantUpdate' branch.id plant.id %}">
    <img class="icon" src="{% static 'main/img/edit-regular.svg' %}"></a>
     <form class="inlineBlock" method="post" action="{% url 'shop:plantDelete' plant.id %}">
        {% csrf_token %}
        <input class="icon deleteConfirm" id='delete' type="image" src="{% static 'main/img/trash-alt-solid.svg' %}">
      </form>
    {% endif %}
    </h1>
    {% if plant.newPrice %}
    <b>原價</b> $ <del>{{ plant.price }}</del><br>
    <b>優惠價</b> $ {{ plant.newPrice }}
    {% else %}
    $ {{ plant.price }}
    {% endif %}
    {% if user.is_superuser %}
    <form id="discNum" action="{% url 'shop:plantDiscount' branch.id plant.id %}">
        {% csrf_token %}
        打<input type="number" name="discount">折
        <input class="btn" type="submit" value="確認">
    </form>
    {% endif %}
    <br>
    庫存 {{ plant.inventory }}<br>
    編碼 {{ plant.code }}<br>
    已有 {{ plant.buyes.count }} 個人買過
    <form id="discNum" action="{% url 'shop:plantBuy' plant.id %}">
        {% csrf_token %}
        <input id="buyBtn" type="submit" value="BUY">
    </form>
    
    </p> 
    </div> 
</div>


{% endblock %}

hanlin/shop/templates/shop/plantSearch.html
{% extends 'main/base.html' %}
{% load staticfiles %}
{% block css %}<link rel="stylesheet" href="{% static 'shop/css/shop.css' %}"> {% endblock %}
{% block content %}
<div id="contentSearch">
<h2 class="four">搜尋結果</h2>
{% if not plants %}
  <p>查無資料</p>
{% else %}
  {% for plant in plants %}
  <div class="plantImg"><P>{{ plant.plantName }}</P><a href="{% url 'shop:plantRead' plant.branch.id plant.id %}"><img src="/static/main/img/{{ plant.url }}"></a>
    <p>
    $ {{ plant.price }}<br>
    庫存 {{ plant.inventory }}
    </p>  
  </div> 
{% endfor %}
{% endif %}
</div>
{% endblock %}

hanlin/shop/templates/shop/shop.html
{% extends 'main/base.html' %}
{% load staticfiles%}
{% block css %}<link rel="stylesheet" href="{% static 'shop/css/shop.css' %}"> {% endblock %}
{% block content %}
{% include 'main/messages.html' %}
<aside>
<ul>
    <li class="classheader">多肉種類</li>
{% for branch, plants in branches.items %}
    <li><a class="classtitle" href="{% url 'shop:branchRead' branch.id %}">{{ branch.branchName }}</a></li>
    {% for plant in plants %}
    <li><a href="{% url 'shop:plantRead' branch.id plant.id %}">{{ plant.plantName }}</a></li>
    {% endfor %}
{% endfor %}
  </ul>
</aside>

<div id="contentRight">
{% for branch, plants in branches.items %}
  <div class="titleImg"><P>
  {{ branch.branchName }}
      {% if user.is_superuser %}
      <form class="inlineBlock" method="post" action="{% url 'shop:branchDelete' branch.id %}">
        {% csrf_token %}
        <input class="icon deleteConfirm" id='delete' type="image" src="{% static 'main/img/trash-alt-solid.svg' %}">
      </form>
      {% endif %}
  </P>
  <a href="{% url 'shop:branchRead' branch.id %}"><img src="/static/main/img/{{ branch.url }}"></a></div> 
{% endfor %}
{% if user.is_superuser %}
<div class="titleImg"><P>New</P><a class='newItem' href="{% url 'shop:branchCreate' %}">+</a></div>
{% endif %}
</div>


{% endblock %}