hanlin/account/urls.py
from django.urls import path
from account import views

app_name = 'account'
urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

hanlin/hanlin/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls', namespace='main')),
    path('shop/', include('shop.urls', namespace='shop')),
    path('account/', include('account.urls', namespace='account')),
    path('new/', include('new.urls', namespace='new')),
    path('order/', include('order.urls', namespace='order')),
    re_path('.*', views.main)
]

hanlin/main/urls.py
from django.urls import path
from main import views


app_name = 'main'
urlpatterns = [
    path('', views.main, name='main'),
    path('contact/', views.contact, name='contact'),
    path('news/', views.news, name='news'),
]

hanlin/new/urls.py
from django.urls import path
from new import views


app_name = 'new'
urlpatterns = [
    path('', views.new, name='new'),
    path('articleCreate/', views.articleCreate, name='articleCreate'),
    path('articleRead/<int:articleId>', views.articleRead, name='articleRead'),
    path('articleUpdate/<int:articleId>', views.articleUpdate, name='articleUpdate'),
    path('articleDelete/<int:articleId>', views.articleDelete, name='articleDelete'),
]

hanlin/order/urls.py
from django.urls import path
from order import views


app_name = 'order'
urlpatterns = [
    path('', views.order, name='order'),
    path('orderDelete/<int:orderId>', views.orderDelete, name='orderDelete'),
]

hanlin/shop/urls.py
from django.urls import path
from shop import views


app_name = 'shop'
urlpatterns = [
    path('', views.shop, name='shop'),
    path('branchCreate/', views.branchCreate, name='branchCreate'),
    path('branchRead/<int:branchId>', views.branchRead, name='branchRead'),
    path('plantRead/<int:branchId>/<int:plantId>', views.plantRead, name='plantRead'),
    path('plantCreate/<int:branchId>', views.plantCreate, name='plantCreate'),
    path('branchUpdate/<int:branchId>', views.branchUpdate, name='branchUpdate'),
    path('plantUpdate/<int:branchId>/<int:plantId>', views.plantUpdate, name='plantUpdate'),
    path('branchDelete/<int:branchId>', views.branchDelete, name='branchDelete'),
    path('plantDelete/<int:plantId>', views.plantDelete, name='plantDelete'),
    path('plantSearch/', views.plantSearch, name='plantSearch'),
    path('plantDiscount/<int:branchId>/<int:plantId>', views.plantDiscount, name='plantDiscount'),
    path('plantBuy/<int:plantId>', views.plantBuy, name='plantBuy'),
]

hanlin/main/models.py
from django.db import models

# Create your models here.

hanlin/new/models.py
from django.db import models

# Create your models here.
class New(models.Model):
    title = models.CharField(max_length=128, unique=True)
    content = models.TextField()
    pubDateTime = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ['-pubDateTime']

hanlin/new/forms.py
from django import forms
from new.models import New


class NewForm(forms.ModelForm):
    title = forms.CharField(label='標題', max_length=128)
    content = forms.CharField(label='內容', widget=forms.Textarea)

    class Meta:
        model = New
        fields = ['title', 'content']

hanlin/main/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.urls.base import reverse
from shop.models import Plant
from django.db.models.query_utils import Q
# Create your views here.



def main(request):
    plants = Plant.objects.filter(Q(hot__icontains=True))
    dicPlants = Plant.objects.filter(Q(discount__lte=5) & Q(discount__gt=0))
    context = {'plants':plants,'dicPlants':dicPlants}
    return render(request, 'main/main.html', context)

def contact(request):
    return render(request, 'main/contact.html')

def news(request):
    return render(request, 'main/news.html')

def admin_required(func):
    def auth(request, *args, **kwargs):
        if not request.user.is_superuser:
            messages.error(request, '請以管理者身份登入')
            return redirect(reverse('account:login') + '?next=' + request.get_full_path())
        return func(request, *args, **kwargs)
    return auth

hanlin/new/views.py
from django.shortcuts import render, redirect, get_object_or_404
from new.models import New
from new.forms import NewForm
from django.contrib import messages
from main.views import admin_required
# Create your views here.

def new(request):
    articles = New.objects.all()
    context = {'articles':articles}
    return render(request, 'new/new.html', context)

@admin_required
def articleCreate(request):
    template = 'new/articleCreateUpdate.html'
    if request.method == 'GET':
        return render(request, template, {'newForm':NewForm()})
    
    # POST
    newForm = NewForm(request.POST)
    if not newForm.is_valid():
        return render(request, template, {'newForm':newForm})
    newForm.save()
    messages.success(request, '文章已新增')
    return redirect('new:new')

def articleRead(request, articleId):
    article = get_object_or_404(New, id=articleId)
    context = {
        'article': article,
    }
    return render(request, 'new/articleRead.html', context)

@admin_required
def articleUpdate(request, articleId):
    article = get_object_or_404(New, id=articleId)
    template = 'new/articleCreateUpdate.html'
    if request.method == 'GET':
        newForm = NewForm(instance=article)
        return render(request, template, {'newForm':newForm})
    
    #POST
    newForm = NewForm(request.POST, instance=article)
    if not newForm.is_valid():
        return render(request, template, {"newForm":newForm})
    newForm.save()
    messages.success(request, '公告已修改')
    return redirect('new:articleRead', articleId=articleId)

@admin_required
def articleDelete(request, articleId):
    if request.method == 'GET':
        return new(request)
    #POST
    article = get_object_or_404(New, id=articleId)
    article.delete()
    messages.success(request, '公告已刪除')
    return redirect('new:new')

hanlin/main/templates/main/base.html
<!doctype html> 
{% load staticfiles %}
<html> 
<head> 
<meta charset="utf-8"> 
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<link rel="stylesheet" href="{% static 'main/css/main5.css' %}"> 
{% block css %}{% endblock %}
</head> 
<body> 

<div id="wrapper">

<header class="four">
<div id="headerBig">
  <div id=headerLeft>
  <img id="headerHanlin" src="{% static 'main/img/hanlin.jpg' %}">瀚霖園多肉植物
  </div>
<div id="search">
  <form class="inlineBlock" action="{% url 'shop:plantSearch' %}">
      <input type="text" name="searchTerm" {% if searchTerm %}value="{{ searchTerm }}"{% endif %}>
      <input class="edit icon" type="image" src="{% static 'main/img/search-solid.svg' %}">
    </form> 
  </div> 
</div>
<nav>
  
     {% include 'main/menu.html' %}
  </nav>
</header>

<div id="headerHidden"></div>
<div id="content">
{% block content %}{% endblock %}
</div>  <!-- content -->


<footer>
 <div id="footerright">
  <img id="footerimg" src="{% static 'main/img/fb.png' %}">
  <p><a id="noneDecration" href="https://www.facebook.com/groups/hanlinyuan6058/?ref=bookmarks">FB粉絲團</a></p>
  </div>
  <div id="footerleft">
   <img id="footerimg" src="{% static 'main/img/hanlin.jpg' %}" href="https://www.facebook.com/groups/hanlinyuan6058/">
    {% include 'main/menu.html' %}
  </div>
</footer>

</div>  <!-- wrapper -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src={% static 'main/js/deleteConfirm.js' %}></script>
  <script src={% static 'main/js/nav.js' %}></script>
</body>
</html>

hanlin/main/templates/main/contact.html
{% extends 'main/base.html' %}
{% load staticfiles %}
{% block content %}
<img id="contactHanlin" src="{% static 'main/img/contact.jpg' %}">
{% endblock %}

hanlin/main/templates/main/main.html
{% extends 'main/base.html' %}
{% load staticfiles %}
{% block css %}
<link rel="stylesheet" href="{% static 'shop/css/shop.css' %}"> 
{% endblock %}
{% block content %}
{% include 'main/messages.html' %}
<div id="contentSearch">
<h2 class="four">熱門商品</h2>
{% for plant in plants %}
  <div class="hotImg four"><P class="hotName"><b>{{ plant.plantName }}</b></P><a href="{% url 'shop:plantRead' plant.branch.id plant.id %}"><img src="/static/main/img/{{ plant.url }}"></a>
    <p>
    $ {{ plant.price }}<br>
    庫存 {{ plant.inventory }}
    </p>  
  </div> 
{% endfor %}

<h2 class="four">特價商品<span>5折起</span></h2>
{% for plant in dicPlants %}
  <div class="hotImg four"><P class="hotName"><b>{{ plant.plantName }}</b></P><a href="{% url 'shop:plantRead' plant.branch.id plant.id %}"><img src="/static/main/img/{{ plant.url }}"></a>
    <p>
    $ <del>{{ plant.price }}</del><br>
     $ {{ plant.newPrice }}<br>
    庫存 {{ plant.inventory }}
    </p>  
  </div> 
{% endfor %}
</div>
{% endblock %}

hanlin/main/templates/main/menu.html
 <ul>
      <li><a href="{% url 'main:main' %}">首頁</a></li>
      <li><a href="{% url 'shop:shop' %}">商品</a></li>
      <li><a href="{% url 'order:order' %}">訂單</a></li>
      <li><a href="{% url 'new:new' %}">最新消息</a></li>
      <li><a href="{% url 'main:contact' %}">聯絡我們</a></li>
      {% if user.is_authenticated %}
      <li><a href="{% url 'account:logout' %}">登出 ({{ user.username }})</a></li>
      {% else %}
      <li><a href="{% url 'account:register' %}">註冊</a></li>
      <li><a href="{% url 'account:login' %}">登入</a></li>
      {% endif %}
    </ul>
    <a id="pull" href="#">清單</a>
      <div style="clear: both;"></div>

hanlin/main/templates/main/messages.html
{% for message in messages %}
      <p class="{{ message.tags }}">{{ message }}</p>
{% endfor %}

hanlin/main/templates/main/news.html
{% extends 'main/base.html' %}
{% load staticfiles %}
{% block content %}
<h2 class="four">最新消息</h2>
<div class="tableDiv">
<table class="table table-striped table-hover">
<tr>
<th>日期</th>
<th>事項</th>
</tr>
<tr>
<td>9/14</td>
<td><a href=/"">活動</a></td>
</tr>
<tr>
<td>9/14</td>
<td><a href=/"">特價活動</a></td>
</tr>
<tr>
<td>9/14</td>
<td><a href="/">維護公告</a></td>
</tr>
<tr>
<td>9/14</td>
<td><a href=/"">45654</a></td>
</tr>
<tr>
<td colspan="2"><a href="/"><img class="icon" src="{% static 'main/img/plus-circle-solid.svg' %}"></a></td>
</tr>
</table>
</div>
{% endblock %}