hanlin/hanlin/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls', namespace='main')),
    path('shop/', include('shop.urls', namespace='shop')),
    path('account/', include('account.urls', namespace='account')),
    path('new/', include('new.urls', namespace='new')),
    path('order/', include('order.urls', namespace='order')),
    re_path('.*', views.main)
]

hanlin/new/urls.py
from django.urls import path
from new import views


app_name = 'new'
urlpatterns = [
    path('', views.new, name='new'),
    path('articleCreate/', views.articleCreate, name='articleCreate'),
    path('articleRead/<int:articleId>', views.articleRead, name='articleRead'),
    path('articleUpdate/<int:articleId>', views.articleUpdate, name='articleUpdate'),
    path('articleDelete/<int:articleId>', views.articleDelete, name='articleDelete'),
]

hanlin/new/models.py
from django.db import models

# Create your models here.
class New(models.Model):
    title = models.CharField(max_length=128, unique=True)
    content = models.TextField()
    pubDateTime = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ['-pubDateTime']

hanlin/new/forms.py
from django import forms
from new.models import New


class NewForm(forms.ModelForm):
    title = forms.CharField(label='標題', max_length=128)
    content = forms.CharField(label='內容', widget=forms.Textarea)

    class Meta:
        model = New
        fields = ['title', 'content']

hanlin/new/views.py
from django.shortcuts import render, redirect, get_object_or_404
from new.models import New
from new.forms import NewForm
from django.contrib import messages
from main.views import admin_required
# Create your views here.

def new(request):
    articles = New.objects.all()
    context = {'articles':articles}
    return render(request, 'new/new.html', context)

@admin_required
def articleCreate(request):
    template = 'new/articleCreateUpdate.html'
    if request.method == 'GET':
        return render(request, template, {'newForm':NewForm()})
    
    # POST
    newForm = NewForm(request.POST)
    if not newForm.is_valid():
        return render(request, template, {'newForm':newForm})
    newForm.save()
    messages.success(request, '文章已新增')
    return redirect('new:new')

def articleRead(request, articleId):
    article = get_object_or_404(New, id=articleId)
    context = {
        'article': article,
    }
    return render(request, 'new/articleRead.html', context)

@admin_required
def articleUpdate(request, articleId):
    article = get_object_or_404(New, id=articleId)
    template = 'new/articleCreateUpdate.html'
    if request.method == 'GET':
        newForm = NewForm(instance=article)
        return render(request, template, {'newForm':newForm})
    
    #POST
    newForm = NewForm(request.POST, instance=article)
    if not newForm.is_valid():
        return render(request, template, {"newForm":newForm})
    newForm.save()
    messages.success(request, '公告已修改')
    return redirect('new:articleRead', articleId=articleId)

@admin_required
def articleDelete(request, articleId):
    if request.method == 'GET':
        return new(request)
    #POST
    article = get_object_or_404(New, id=articleId)
    article.delete()
    messages.success(request, '公告已刪除')
    return redirect('new:new')

hanlin/new/templates/new/articleCreateUpdate.html
{% extends 'main/base.html' %}
{% load staticfiles %}
<h2>
  {% if articleForm.instance.id %}
    修改文章
  {% else %}
    新增文章
  {% endif %}
</h2>
{% block content %}
    {% if newForm.instance.id %}
    <form method="post" action="{% url 'new:articleUpdate' newForm.instance.id %}">
    {% else %}
    <form method="post" action="{% url 'new:articleCreate' %}">
    {% endif %}  
      {% csrf_token %}
      {{ newForm.as_p }}
      <input class="btn" type="submit" value="送出">
      <a class="btn" href="{% url 'new:new' %}">放棄</a>
    </form>
  </body>
</html>
{% endblock %}

hanlin/new/templates/new/articleRead.html
{% extends 'main/base.html' %}
{% load staticfiles %}
{% block content %}
<div id="newTitle">
<h1>{{ article.title }}</h1>
{% if user.is_superuser %}
   <a class="btn inlineBlock" href="{% url 'new:articleUpdate' article.id %}">修改</a>
{% endif %}
<h3>發布時間 : {{ article.pubDateTime }}</h3>
</div>
<div id="newReadBorder">
{{ article.content|linebreaks }}
</div>

{% endblock %}

hanlin/new/templates/new/new.html
{% extends 'main/base.html' %}
{% load staticfiles %}
{% block content %}
{% include 'main/messages.html' %}
<h2 class="four">最新消息</h2>
<div class="tableDiv">
<table class="table table-striped table-hover">
<tr>
<th>日期</th>
<th>事項</th>
</tr>
{% for article in articles %}
<tr>
<td>{{ article.pubDateTime }}</td>
<td><a href="{% url 'new:articleRead' article.id %}">{{　article.title }}</a>
{% if user.is_superuser %}
      <form class="inlineBlock" method="post" action="{% url 'new:articleDelete' article.id %}">
      {% csrf_token %}
      <input class="btn deleteConfirm" type="submit" value="刪除">
      </form>
{% endif %}
</td>
</tr>
{% endfor %}
<tr>
<td colspan="2"><a href="{% url 'new:articleCreate' %}"><img class="icon" src="{% static 'main/img/plus-circle-solid.svg' %}"></a></td>
</tr>
</table>
</div>
{% endblock %}